global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fl_server'
    static_configs:
      - targets: ['fl_server:9090']

  - job_name: 'model_api'
    static_configs:
      - targets: ['model_api:8000']
